require 'fileutils'

ROOT = Dir.pwd
BUILD_DIR = "#{ROOT}/__BUILD"

INPUT_EXCEL_FPATH = "#{ROOT}/@EXCEL/sample.xlsx"
TEMPLATE_DIR      = "#{ROOT}/@CUSTOM/template_db"
OUTPUT_CS_DIR     = "#{ROOT}/@CUSTOM/AutoGenerated.DB/output"
GEN_DLL_FPATH     = "#{ROOT}/@CUSTOM/AutoGenerated.DB/bin/Debug/net35/AutoGenerated.DB.dll"
GEN_DB_FPATH      = "#{BUILD_DIR}/DB.db"
PASSWORD          = "helloworld"


task :default do
  FileUtils::mkdir_p BUILD_DIR


  Dir.chdir('NF.CLI.ClassGenerator') do
    sh 'dotnet restore'
    sh "dotnet run -- -e #{INPUT_EXCEL_FPATH} -t #{TEMPLATE_DIR} -o #{OUTPUT_CS_DIR}"
  end

  Dir.chdir('SQLite.Attribute') do
    sh 'dotnet restore'
    sh "dotnet build"
  end

  Dir.chdir('@CUSTOM/AutoGenerated.DB') do
    sh 'dotnet restore'
    sh "dotnet build"
  end

  Dir.chdir('NF.CLI.DataExporter') do
    sh 'dotnet restore'
    sh "dotnet run -- -d #{GEN_DLL_FPATH} -e #{INPUT_EXCEL_FPATH} -o #{GEN_DB_FPATH} -p #{PASSWORD}"
  end

  cp_r "#{ROOT}/@CUSTOM/AutoGenerated.DB/bin/Debug/net35/.", BUILD_DIR, :preserve => true
end
