using System.Collections.Generic;
using AutoGenerated.ComplexOne;
using UnityEngine;

namespace Hello.Complex
{
	public class ComplexMain : MonoBehaviour
	{
		void Start()
		{
			DataService ds = new DataService("Assets/Hello.Complex/output/output.db", "");
			List<DCharacter> characters = ds.Gets<DCharacter>();
			foreach (DCharacter c in characters)
			{
				Debug.Log($"{c.id} | {c.isSpecial} | {c.xDT} | {c.xDateTimeOffset.ToLocalTime()} | {c.xTimeSpan}");
			}
		}
	}
}