using CommandLine;
using System.Collections.Generic;

namespace NF.Tools.DataFlow
{
    [Verb("code-gen", HelpText = "generate code from exel.")]
    public class DataFlowRunnerOption
    {
        [Option('i', "input_paths", Required = true)]
        public IEnumerable<string> InputExcelPaths { get; set; }

        [Option('o', "output_code_dir", Default = "output", HelpText = "output directory (default: output)")]
        public string OutputCodeDir { get; set; }

        [Option('o', "output_db_path", Default = "output.db", HelpText = "output db path (default: output.db)")]
        public string OutputDbPath { get; set; }

        [Option('p', "password", Required = false, HelpText = "db password")]
        public string Password { get; set; }

        [Option('n', "namespace", Default = "AutoGenerated.DB", HelpText = "namespace (default: AutoGenerated.DB)")]
        public string Namespace { get; set; }

        // TODO(pyoung): template는 하나로 줄이고
        [Option('t', "template_dir")]
        public string TemplateDir { get; set; }

        [Option("template_const")]
        public string TemplateConstPath { get; set; }

        [Option("template_enum")]
        public string TemplateEnumPath { get; set; }

        [Option("template_class")]
        public string TemplateClassPath { get; set; }

        // TODO(pyoung): config도 처리
        [Option('c', "config")]
        public string ConfigFpath { get; set; }

        // TODO(pyoung): 아싸리 커스텀 sln폴더를 포함시켜 빌드시키게 하는 걸 옵션으로 주면 어떨까?
    }
}