using CommandLine;
using System.Collections.Generic;

namespace NF.Tools.DataFlow.CodeGen
{
    [Verb("code-gen", HelpText = "generate code from exel.")]
    public class CodeGeneratorOptions
    {
        [Option('i', "input_paths", Required = true)]
        public IEnumerable<string> InputExcelPaths { get; set; }

        [Option('o', "output_dir", Default = "output", HelpText = "output directory (default: output)")]
        public string OutputDir { get; set; }

        [Option('c', "config")]
        public string ConfigFpath { get; set; }

        [Option('t', "template_dir")]
        public string TemplateDir { get; set; }

        [Option('n', "namespace", Default = "AutoGenerated.DB", HelpText = "namespace (default: AutoGenerated.DB)")]
        public string Namespace { get; set; }

        [Option("template_const")]
        public string TemplateConstPath { get; set; }

        [Option("template_enum")]
        public string TemplateEnumPath { get; set; }

        [Option("template_class")]
        public string TemplateClassPath { get; set; }
    }
}