using CommandLine;
using System.Collections.Generic;

namespace NF.Tools.DataFlow
{
    [Verb("code-gen", HelpText = "generate code from exel.")]
    public class DataFlowRunnerOption
    {
        [Option('i', "input_paths", Default = new string[] { "input" })]
        public IEnumerable<string> input_paths { get; set; }

        [Option('a', "pre_assemble", Default = true)]
        public bool pre_assemble { get; set; }

        [Option('o', "output_code_dir", Default = "output", HelpText = "output directory")]
        public string output_code_dir { get; set; }

        [Option('o', "output_db_path", Default = "output.db", HelpText = "output db path")]
        public string output_db_path { get; set; }

        [Option('p', "password", Required = false, HelpText = "db password")]
        public string password { get; set; }

        [Option('n', "namespace", Default = "AutoGenerated.DB", HelpText = "namespace")]
        public string @namespace { get; set; }

        [Option('t', "template_paths", Default = null)]
        public IEnumerable<string> template_paths { get; set; }

        [Option('c', "config", Default = ".dataflow.yaml", HelpText = "config file path")]
        public string config { get; set; }

        public void Merge(in DataFlowRunnerOption o)
        {
            if (this.input_paths == null)
            {
                this.input_paths = o.input_paths;
            }

            this.pre_assemble = o.pre_assemble;

            if (this.output_code_dir == null)
            {
                this.output_code_dir = o.output_code_dir;
            }
            if (this.output_db_path == null)
            {
                this.output_db_path = o.output_db_path;
            }
            if (this.password == null)
            {
                this.password = o.password;
            }
            if (this.@namespace == null)
            {
                this.@namespace = o.@namespace;
            }
            if (this.template_paths == null)
            {
                this.template_paths = o.template_paths;
            }
            // NOTE(pyoung): pass - ConfigFpath 
        }

        // TODO(pyoung): 아싸리 커스텀 sln폴더를 포함시켜 빌드시키게 하는 걸 옵션으로 주면 어떨까?
    }
}