using System.Collections.Generic;
using AutoGenerated.DB;
using UnityEngine;

namespace Hello
{
	public class main : MonoBehaviour
	{
		void Start()
		{
			DataService ds = new DataService("Assets/output/output.db", "");
			List<DCharacter> characters = ds.Gets<DCharacter>();
			foreach (DCharacter c in characters)
			{
				Debug.Log($"{c.id} | {c.character_id} | {c.level} | {c.name}");
			}
		}
	}
}