using System;
using System.ComponentModel;

namespace AutoGenerated.ComplexOne
{
    public enum E_ENUM
    {
        
        [Description("할로우")]
        n1 = 10,
        
        [Description("helelo")]
        n2 = 20,
        
        [Description("ASDF")]
        n3 = 30,
        
        [Description("ASDF")]
        n4 = 40,
        
        [Description("ASDF")]
        n5 = 50,
        
        [Description("ASDF")]
        n6 = 60,
    }
}