using NF.Tools.DataFlow;
using System.IO;
using System.Windows.Forms;

namespace DataFlowGUI
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void lstFiles_DragDrop(object sender, DragEventArgs e)
        {
            var xx = e.Data.GetDataPresent("FileDrop");
            if (!xx)
            {
                return;
            }
            var dd = e.Data.GetData("FileDrop");
            if (dd == null)
            {
                return;
            }
            string[] paths = dd as string[];
            if (paths == null)
            {
                return;
            }

            DataFlowRunnerOption opt = new DataFlowRunnerOption
            {
                input_paths = paths,
                @namespace= "AutoGenerated.DB",
                output_code_dir = "C:/temp",
                output_db_path = "C:/temp/output.db",
            };
            int ret = DataFlowRunner.Run(opt);
        }

        private void lstFiles_DragEnter(object sender, DragEventArgs e)
        {
            e.Effect = DragDropEffects.Link;
        }

        private void lstFiles_DragOver(object sender, DragEventArgs e)
        {

        }
    }
}