/*
 * generated 8/8/2018 12:57:53 AM
 */
namespace AutoGenerated.DB
{
    using System;
    using SQLite.Attribute;

    
    [Export]
    public class SampleCharacter
    {
        
        [Unique]
        public int id { get; set; }
        public int character_id { get; set; }
        public string name { get; set; }
        [Obsolete]
        public int level { get; set; }
    }
    
}
