/*
 * generated 
 */
using System;

namespace AutoGenerated.DB
{
       	
       	public enum E_SAMPLE
       	{
       		hello,
       		world,
       		nice,
       		to,
       		meet,
       		you,
       		
       	}
       	[Flags]
       	public enum E_HELLO
       	{
       		A=1 << 0,
       		B = 1 << 2,
       		C =1 << 3,
       		D = A | B | C,
       		
       	}
       	[Flags]
       	public enum E_HELLO2
       	{
       		hello,
       		world,
       		nice,
       		to,
       		meet,
       		you,
       		
       	}
       	public enum ItemType
       	{
       		Gold,
       		ActionCharge,
       		
       	}
}