using System.ComponentModel;

namespace AutoGenerated.DB
{
    public class CONST
    {
        
        [Description("할로우")]
        public const int n1 = 1;
        
        [Description("helelo")]
        public const string n2 = "2";
        
        [Description("ASDF")]
        public const int n3 = 3;
        
        [Description("ASDF")]
        public const int n4 = 4;
        
        [Description("ASDF")]
        public const int n5 = 5;
        
        [Description("ASDF")]
        public const string n6 = "6";
    }
}