using System;
using SQLite.Attributes;
using System.ComponentModel;

namespace AutoGenerated.DB
{
    [Export]
    public class DCharacter
    {
        [PrimaryKey]
        [Description("아이디")]
        public int id { get; set; }
        [Unique]
        [Description("캐릭터아이디")]
        public int character_id { get; set; }
        
        [Description("이름")]
        public string name { get; set; }
        
        [Description("레벨")]
        public int level { get; set; }
    }
}