using System;
using System.ComponentModel;

namespace AutoGenerated.DB
{
    public enum E_ENUM
    {
        
        [Description("할로우")]
        n1 = 1,
        
        [Description("helelo")]
        n2 = 2,
        
        [Description("ASDF")]
        n3 = 3,
        
        [Description("ASDF")]
        n4 = 4,
        
        [Description("ASDF")]
        n5 = 5,
        
        [Description("ASDF")]
        n6 = 6,
    }
}